# The API key fo webpagetest.org
# Try not to push it to github :)
#key = "_API_KEY_"

# domain list
domains = "top100.txt"

# The start and end index of the domains we're testing
start = 0
end = 100

# Number of Tests to Run (up to 100)
runs = 30

# Task priority (0 to 9, highest: 0, lowest: 9, default: 5)
priority = 5

# do not run cache view
fvonly = 1

# Use http://www.webpagetest.org/getLocations.php?f=xml to hunt for locations and UAs
locations = ['Necko:Gecko', 'Necko:Firefox-Nightly', 'Necko:Chrome']

labels = []
endpoint = "http://wpt.xeon.tw/runtest.php"
pingback = "http://presto.xeon.tw/api/addDomain"
